Create blackjack3.py
I am running it on python 3.3.2. I don't know the root cause of 'index out of range error' on line 312.  File "blackj3.py", line 371, in <module>
    draw()
  File "blackj3.py", line 312, in draw
    table_area.coords(card[52], 0,800)
IndexError: list index out of range

I will appreciate if someone can help me fiish up this code. I am a newbie to python and I need help as soon as possible since I have already spend more than a week on this program. Any help will appreciated.